main:AC2Tier.o AC3Tier.o ACChairCar.o ACFirstClass.o Application.o Booking.o Date.o FirstClass.o Gender.o Passenger.o Railways.o SecondSitting.o Sleeper.o Station.o Tatkal.o TatkalBooking.o Blind.o BlindBooking.o Cancer.o CancerBooking.o General.o GeneralBooking.o Handicapped.o HandicappedBooking.o Ladies.o LadiesBooking.o PremiumTatkal.o PremiumTatkalBooking.o SeniorCitizen.o SeniorCitizenBooking.o
	g++ AC2Tier.o AC3Tier.o ACChairCar.o ACFirstClass.o Application.o Booking.o Date.o FirstClass.o Gender.o Passenger.o Railways.o SecondSitting.o Sleeper.o Station.o Tatkal.o TatkalBooking.o Blind.o BlindBooking.o Cancer.o CancerBooking.o General.o GeneralBooking.o Handicapped.o HandicappedBooking.o Ladies.o LadiesBooking.o PremiumTatkal.o PremiumTatkalBooking.o SeniorCitizen.o SeniorCitizenBooking.o -o main
Station.o:Station.cpp
	g++ -c Station.cpp
AC2Tier.o:AC2Tier.cpp
	g++ -c AC2Tier.cpp
AC3Tier.o:AC3Tier.cpp
	g++ -c AC3Tier.cpp
ACChairCar.o:ACChairCar.cpp
	g++ -c ACChairCar.cpp
ACFirstClass.o:ACFirstClass.cpp
	g++ -c ACFirstClass.cpp
Application.o:Application.cpp
	g++ -c Application.cpp
Booking.o:Booking.cpp
	g++ -c Booking.cpp
Date.o:Date.cpp
	g++ -c Date.cpp
FirstClass.o:FirstClass.cpp
	g++ -c FirstClass.cpp
Gender.o:Gender.cpp
	g++ -c Gender.cpp
Passenger.o:Passenger.cpp
	g++ -c Passenger.cpp
Railways.o:Railways.cpp
	g++ -c Railways.cpp
SecondSitting.o:SecondSitting.cpp
	g++ -c SecondSitting.cpp
Sleeper.o:Sleeper.cpp
	g++ -c Sleeper.cpp
Tatkal.o:Tatkal.cpp
	g++ -c Tatkal.cpp
TatkalBooking.o:TatkalBooking.cpp
	g++ -c TatkalBooking.cpp
Blind.o:Blind.cpp
	g++ -c Blind.cpp
BlindBooking.o:BlindBooking.cpp
	g++ -c BlindBooking.cpp
Cancer.o:Cancer.cpp
	g++ -c Cancer.cpp
CancerBooking.o:CancerBooking.cpp
	g++ -c CancerBooking.cpp
General.o:General.cpp
	g++ -c General.cpp
GeneralBooking.o:GeneralBooking.cpp
	g++ -c GeneralBooking.cpp
Handicapped.o:Handicapped.cpp
	g++ -c Handicapped.cpp
HandicappedBooking.o:HandicappedBooking.cpp
	g++ -c HandicappedBooking.cpp
Ladies.o:Ladies.cpp
	g++ -c Ladies.cpp
LadiesBooking.o:LadiesBooking.cpp
	g++ -c LadiesBooking.cpp
PremiumTatkal.o:PremiumTatkal.cpp
	g++ -c PremiumTatkal.cpp
PremiumTatkalBooking.o:PremiumTatkalBooking.cpp
	g++ -c PremiumTatkalBooking.cpp
SeniorCitizen.o:SeniorCitizen.cpp
	g++ -c SeniorCitizen.cpp
SeniorCitizenBooking.o:SeniorCitizenBooking.cpp
	g++ -c SeniorCitizenBooking.cpp
